### ISSUE TITLE
About the relevant datasets and trained models in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [valeriopaolicelli/adageo-WACV2021#4]
Hello, @francescomontagna @valeriopaolicelli @gmberton ,I really appreciate for your work！Congratulations :)

I would like to ask where the datasets and trained models involved in this article can be obtained? Is it convenient to provide？

I am always looking forward to your kind response.
Best regards.

**Comment by gmberton** [comment]
To download the dataset you can check out this repository https://github.com/gmberton/VPR-datasets-downloader
We do not plan to release trained models
